name: Test & Deploy Build Images

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 10 * * 0"
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  
  test:
    name: pytest integration test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup up Python 3.8      
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install test dependencies
        working-directory: ./tests/integration
        run: |
          pip3 install -r requirements.dev.txt
      
      - name: Run integration tests
        working-directory: ./tests/integration
        run: |
          chmod +x ./scripts/01-run-tests.sh
          ./scripts/01-run-tests.sh
  
        
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: clone repo
        uses: actions/checkout@v2
        
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha     
            type=raw,value=latest,enable={{is_default_branch}}
            #image is using node red 3.1.0 w/ node v18
            type=raw,value=3.1.0-18,enable={{is_default_branch}}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Build and Push Image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          target: prod
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
